Allow non-array json string
hyperjumptech/grule-rule-engine pull request #203
Opened 2021-07-08 05:37 UTC by sw7190

Allow non-array json string to ParseJSONRuleset

2021-07-10 13:32 UTC, niallnsec commented
Hi sw7190,

The ParseJSONRuleset function is explicitly meant to parse a JSON ruleset into GRL syntax and as such expects the input to be an array of JSON objects. I think parsing a single JSON rule into GRL syntax would call for a separate function to be defined called ParseJSONRule which would do what you are after. Beyond that I think it makes sense to have a ParseJSONRule function anyway since it would be useful to anyone storing GRL/JSON rules in a database table or similar storage.

I am assuming you want to be able to load a single rule using the JSONResource loader, is that correct? If that is the case, I think a cleaner approach is to define a new function as described above and then in JSONResource.Load we can switch on the first rune of the input data. If it is a '[' we would call ParseJSONRuleset and if it is. a '{' we would call ParseJSONRule.

2021-07-11 06:42 UTC, sw7190 commented
> Hi sw7190,
> 
> The ParseJSONRuleset function is explicitly meant to parse a JSON ruleset into GRL syntax and as such expects the input to be an array of JSON objects. I think parsing a single JSON rule into GRL syntax would call for a separate function to be defined called ParseJSONRule which would do what you are after. Beyond that I think it makes sense to have a ParseJSONRule function anyway since it would be useful to anyone storing GRL/JSON rules in a database table or similar storage.
> 
> I am assuming you want to be able to load a single rule using the JSONResource loader, is that correct? If that is the case, I think a cleaner approach is to define a new function as described above and then in JSONResource.Load we can switch on the first rune of the input data. If it is a '[' we would call ParseJSONRuleset and if it is. a '{' we would call ParseJSONRule.

Okay. sure!

2021-07-12 07:59 UTC, niallnsec requested changes
This all looks good with the one small change needed to catch any invalid JSON being passed in to the JSONResource Load function.

2021-07-12 07:59 UTC, niallnsec commented on pkg/JsonResource.go
> +	}
```suggestion
	} else {
		err = errors.New("invalid JSON input")
	}
```
Looks good! We just need to catch the extra case where we may have loaded something which is not valid JSON.

2021-07-12 09:10 UTC, sw7190 commented
> JSONResource Load 함수로 전달되는 유효하지 않은 JSON을 잡는 데 필요한 작은 변경 하나만으로 이 모든 것이 좋아 보입니다.

Good!

2021-07-12 09:31 UTC, niallnsec requested changes
Need to fix missing import causing build failure

2021-07-12 09:31 UTC, niallnsec commented on pkg/JsonResource.go
>  	"encoding/json"
```suggestion
	"encoding/json"
	"errors"
```

2021-07-12 09:33 UTC, niallnsec approved these changes

2021-07-12 13:12 UTC, newm4n commented
@sw7190 
Seems your branch is out-of-date
Could your update your branch to the latest upstream master.
I will merge this as soon as its ready.

2021-07-12 23:21 UTC, merged