Feat/engine to resolve #266
hyperjumptech/grule-rule-engine pull request #267
Opened 2021-11-16 14:22 UTC by hjblom

* Add option to error on failed grule engine execution
 * Add unit test cases

2021-11-16 15:45 UTC, newm4n requested changes
Thanks a lot for the contribution.
Could you change the variable name so it become more self explanatory.

Again, thanks.

2021-11-16 15:45 UTC, newm4n commented on engine/GruleEngine.go
> +	ErrorOnFailedExecute bool
Could you use the name like `ReturnErrOnFailedRuleEvaluation`, just to make the variable name become a bit more self explanatory.

2021-11-16 15:53 UTC, hjblom commented
> Thanks a lot for the contribution. Could you change the variable name so it become more self explanatory.
> 
> Again, thanks.

Thanks for the quick review!

2021-11-17 02:24 UTC, newm4n approved these changes
Lets get this merge

2021-11-17 02:24 UTC, merged